FROM nvidia/cuda:11.7.1-devel-ubuntu22.04

RUN apt update && apt upgrade -y
RUN apt install software-properties-common -y
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt install python3.10 -y
RUN apt install python3-pip -y
RUN apt install git -y

WORKDIR /llm-api

COPY ./requirements.txt /llm-api/requirements.txt
RUN pip3 install --no-cache-dir --upgrade -r requirements.txt

COPY ./app /llm-api/app
ENV PYTHONPATH "/llm-api"

RUN pip3 install torch==2.0.0 torchvision==0.15.1 torchaudio==2.0.1 --index-url https://download.pytorch.org/whl/cu117
RUN git clone https://github.com/qwopqwop200/GPTQ-for-LLaMa -b cuda

ENV TORCH_CUDA_ARCH_LIST=8.6
RUN cd GPTQ-for-LLaMa && \
    pip3 install protobuf==3.20 && \
    pip3 install -r requirements.txt && \
    python3 setup_cuda.py install && \
    cd ..

RUN touch GPTQ-for-LLaMa/__init__.py && mv GPTQ-for-LLaMa /llm-api/app/llms/gptq_llama/

CMD ["python3", "./app/main.py"]
